name: C++ CI


on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:11.8.0-devel-ubuntu22.04

    steps:
      # Checkout the repository with submodules
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive # Ensures submodules are initialized and updated

      - name: Verify CUDA installation
        run: |
          nvcc --version
          ls -la /usr/local/cuda/lib64/

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.27'

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run Main
        run: ./build/fft

      - name: Run Tests
        run: ctest --test-dir build --output-on-failure
