name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Cache apt package lists and downloaded .deb files
      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-cache
          restore-keys: |
            ${{ runner.os }}-apt-cache

      # Checkout the repository with submodules
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive # Ensures submodules are initialized and updated

      - name: Install MPI, OpenMP, OpenCV, and libcurl
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenmpi-dev openmpi-bin libomp-dev
          sudo apt-get install -y libopencv-dev
          sudo apt-get install -y libcurl4-openssl-dev


      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.27'

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      #- name: Run Main
      #  run: ./build/main_cpu

      - name: Run Tests
        run: ctest --test-dir build --output-on-failure
